In [2]:
import pandas as pd

df_trn = pd.read_csv('../../01_src/01_CustomerSubscriptionData/.data/customer_cases.csv',index_col=0)
df_cs = pd.read_csv('../../01_src/01_CustomerSubscriptionData/.data/customer_info.csv',index_col=0)
df_prd_cs = pd.read_csv('../../01_src/01_CustomerSubscriptionData/.data/customer_product.csv',index_col=0)
df_prd = pd.read_csv('../../01_src/01_CustomerSubscriptionData/.data/product_info.csv',index_col=0)

In [6]:
df = df_trn[df_trn['reason'] == 'signup'].drop(columns=['reason','channel'])
df = pd.merge(df, df_cs, how='left', left_on='customer_id', right_on='customer_id')
df = pd.merge(df, df_prd_cs, how='left', left_on='customer_id', right_on='customer_id')
df = pd.merge(df, df_prd, how='left', left_on='product', right_on='product_id')

df = df[df['date_time'] >= '2019-01-01']

df

,case_id,date_time,customer_id,age,gender,product,signup_date_time,cancel_date_time,name,price,billing_cycle
27345,CC52120,2019-01-01 07:56:58,C29793,62,female,prd_1,2019-01-01 08:00:46,NaN,annual_subscription,1200,12
27346,CC52122,2019-01-01 08:05:10,C29794,61,male,prd_1,2019-01-01 08:09:32,NaN,annual_subscription,1200,12
27347,CC52124,2019-01-01 08:44:32,C29795,58,male,prd_1,2019-01-01 08:45:42,NaN,annual_subscription,1200,12
27348,CC52126,2019-01-01 08:54:33,C29796,58,male,prd_1,2019-01-01 08:58:46,NaN,annual_subscription,1200,12
27349,CC52127,2019-01-01 08:56:58,C29797,72,female,prd_1,2019-01-01 08:59:29,NaN,annual_subscription,1200,12
...,...,...,...,...,...,...,...,...,...,...,...
129522,CC330493,2021-12-31 14:11:33,C131970,39,female,prd_1,2021-12-31 14:18:00,NaN,annual_subscription,1200,12
129523,CC330498,2021-12-31 14:32:31,C131971,77,male,prd_2,2021-12-31 14:35:23,NaN,monthly_subscription,125,1
129524,CC330502,2021-12-31 14:36:06,C131972,49,male,prd_2,2021-12-31 14:41:15,NaN,monthly_subscription,125,1
129525,CC330515,2021-12-31 15:02:11,C131973,46,male,prd_2,2021-12-31 15:05:48,NaN,monthly_subscription,125,1
129526,CC330527,2021-12-31 15:33:29,C131974,45,male,prd_1,2021-12-31 15:37:13,NaN,annual_subscription,1200,12

In [7]:
df['date_time'].str[:4].unique()

array(['2019', '2020', '2021'], dtype=object)

In [7]:
df.columns = [
  'ケースID', '日時', '顧客ID', '年齢', '性別', '商品', '契約日時', 'キャンセル日時', '商品名', '価格', '更新期間'
]
df

,ケースID,日時,顧客ID,年齢,性別,商品,契約日時,キャンセル日時,商品名,価格,更新期間
0,CC101,2017-01-01 10:32:03,C2448,76,female,prd_1,2017-01-01 10:35:09,NaN,annual_subscription,1200,12
1,CC102,2017-01-01 11:35:47,C2449,61,male,prd_1,2017-01-01 11:39:29,2021-09-05 10:00:02,annual_subscription,1200,12
2,CC103,2017-01-01 11:37:09,C2450,58,female,prd_1,2017-01-01 11:42:00,2019-01-13 16:24:55,annual_subscription,1200,12
3,CC104,2017-01-01 13:28:14,C2451,62,female,prd_2,2017-01-01 13:32:08,NaN,monthly_subscription,125,1
4,CC105,2017-01-01 13:52:22,C2452,71,male,prd_1,2017-01-01 13:57:30,2021-06-28 18:06:01,annual_subscription,1200,12
...,...,...,...,...,...,...,...,...,...,...,...
129522,CC330493,2021-12-31 14:11:33,C131970,39,female,prd_1,2021-12-31 14:18:00,NaN,annual_subscription,1200,12
129523,CC330498,2021-12-31 14:32:31,C131971,77,male,prd_2,2021-12-31 14:35:23,NaN,monthly_subscription,125,1
129524,CC330502,2021-12-31 14:36:06,C131972,49,male,prd_2,2021-12-31 14:41:15,NaN,monthly_subscription,125,1
129525,CC330515,2021-12-31 15:02:11,C131973,46,male,prd_2,2021-12-31 15:05:48,NaN,monthly_subscription,125,1
129526,CC330527,2021-12-31 15:33:29,C131974,45,male,prd_1,2021-12-31 15:37:13,NaN,annual_subscription,1200,12

In [27]:
df.to_csv('data.csv', index=False, encoding='utf-8-sig')